package tfg.test.selenium;

import static org.junit.Assert.*;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class SeleniumTest {

	
	@Test
	public void testSelenium() {
		WebDriver driver  = new FirefoxDriver();
		driver.navigate().to("http://localhost:8080/Tfg");
		String appTitle = driver.getTitle();
		WebDriverWait wait = new WebDriverWait(driver, 4000);
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("head"))));
		WebElement element = driver.findElement(By.id("head"));
		String actualLinkText = element.getText(); 
		assertEquals(actualLinkText, "Welcome to TrekkingApp!");
		element = driver.findElement(By.id("loginLink"));
		element.click();
		for(String winHandle : driver.getWindowHandles()){
            driver.switchTo().window(winHandle);
        }
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("registerLink"))));
		element = driver.findElement(By.id("registerLink"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("loginName"))));
		element = driver.findElement(By.id("loginName"));
		element.sendKeys("fran");
		element = driver.findElement(By.id("password"));
		element.sendKeys("fran");
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("retypePassword"))));
		element = driver.findElement(By.id("retypePassword"));
		element.sendKeys("fran");
		element = driver.findElement(By.id("firstName"));
		element.sendKeys("fran");
		element = driver.findElement(By.id("lastName"));
		element.sendKeys("fran");
		element = driver.findElement(By.id("email"));
		element.sendKeys("fran@fran.com");
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("head"))));
		element = driver.findElement(By.id("head"));
		assertEquals(element.getText(),"Welcome to TrekkingApp!");
		element = driver.findElement(By.id("nombreLoginUsuario"));
		element.click();
		element = driver.findElement(By.linkText("Update profile"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("firstName"))));
		element = driver.findElement(By.id("firstName"));
		element.sendKeys("francisco");
		element = driver.findElement(By.id("lastName"));
		element.sendKeys("francisco");
		element = driver.findElement(By.id("email"));
		element.sendKeys("francisco@francisco.com");
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("head"))));
		element = driver.findElement(By.id("head"));
		assertEquals(element.getText(),"Welcome to TrekkingApp!");
		element = driver.findElement(By.id("nombreLoginUsuario"));
		element.click();
		element = driver.findElement(By.linkText("Change password"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("oldPassword"))));
		element = driver.findElement(By.id("oldPassword"));
		element.sendKeys("fran");
		element = driver.findElement(By.id("newPassword"));
		element.sendKeys("francisco");
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("retypeNewPassword"))));
		element = driver.findElement(By.id("retypeNewPassword"));
		element.sendKeys("francisco");
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("head"))));
		element = driver.findElement(By.id("head"));
		assertEquals(element.getText(),"Welcome to TrekkingApp!");
		element = driver.findElement(By.id("nombreLoginUsuario"));
		element.click();
		element = driver.findElement(By.linkText("Select language"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("language"))));
		WebElement myOption = driver.findElement(By.xpath("//Select[@id='language']/option[normalize-space(text())='Spanish']"));
		myOption.click();
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("head"))));
		element = driver.findElement(By.id("head"));
		assertEquals(element.getText(),"¡Bienvenido a TrekkingApp!");
		element = driver.findElement(By.id("nombreLoginUsuario"));
		element.click();
		element = driver.findElement(By.linkText("Salir"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("head"))));
		element = driver.findElement(By.id("head"));
		assertEquals(element.getText(),"¡Bienvenido a TrekkingApp!");
		element = driver.findElement(By.id("loginLink"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("loginName"))));
		element = driver.findElement(By.id("loginName"));
		element.sendKeys("fran");
		element = driver.findElement(By.id("password"));
		element.sendKeys("francisco");
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.linkText("Buscar ruta"))));
		element = driver.findElement(By.linkText("Buscar ruta"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("nameSearchRoute"))));
		element = driver.findElement(By.id("nameSearchRoute"));
		element.sendKeys("Camino");
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("button"))));
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.linkText("Camino de Santiago Francés"))));
		element = driver.findElement(By.linkText("Camino de Santiago Francés"));
		assertEquals(element.getText(),"Camino de Santiago Francés");
		element = driver.findElement(By.id("routeStart"));
		System.out.println(element.getText());
		assertEquals(element.getText(),"Juan de Pie de Puerto");
		element = driver.findElement(By.id("routeEnd"));
		assertEquals(element.getText(),"Santiago de Compostela");
		element = driver.findElement(By.linkText("Camino de Santiago Francés"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("nombre"))));
		element = driver.findElement(By.id("nombre"));
		assertEquals(element.getText(),"Camino de Santiago Francés");
		element = driver.findElement(By.id("routeStart"));
		assertEquals(element.getText(),"Juan de Pie de Puerto");
		element = driver.findElement(By.id("routeEnd"));
		assertEquals(element.getText(),"Santiago de Compostela");
		element = driver.findElement(By.id("routeKilometers"));
		assertEquals(element.getText(),"780");
		element = driver.findElement(By.id("positiveSlope"));
		assertEquals(element.getText(),"7000");
		element = driver.findElement(By.id("negativeSlope"));
		assertEquals(element.getText(),"15000");
		element = driver.findElement(By.id("numberOfHotels"));
		assertEquals(element.getText(),"780");
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.linkText("Estadísticas de la ruta"))));
		element = driver.findElement(By.linkText("Estadísticas de la ruta"));
		element.click();
		driver.navigate().back();
		element = driver.findElement(By.id("dateStart"));
		element.sendKeys("06/07/2016");
		element = driver.findElement(By.id("dateEnd"));
		element.sendKeys("06/07/2016");
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("button"))));
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("tweetName"))));
		element = driver.findElement(By.id("tweetName"));
		element.click();
		element = driver.findElement(By.id("tweetCreationDate"));
		assertEquals(element.getText(),"miércoles 6 de julio de 2016 21:16");
		element = driver.findElement(By.id("tweetRetweets"));
		assertEquals(element.getText(),"0");
		element = driver.findElement(By.id("tweetFavourites"));
		assertEquals(element.getText(),"0");
		element = driver.findElement(By.id("tweetLatitude"));
		assertEquals(element.getText(),"42,892");
		element = driver.findElement(By.id("tweetLongitude"));
		assertEquals(element.getText(),"-8,419");
		element = driver.findElement(By.id("tweetSentiment"));
		assertEquals(element.getText(),"N");
		driver.navigate().back();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.linkText("Alertas"))));
		element = driver.findElement(By.linkText("Alertas"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.linkText("Ver alertas"))));
		element = driver.findElement(By.linkText("Ver alertas"));
		element.click();
		element = driver.findElement(By.id("dateStart"));
		element.sendKeys("06/07/2016");
		element = driver.findElement(By.id("dateEnd"));
		element.sendKeys("07/07/2016");
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("alertName"))));
		element = driver.findElement(By.id("alertName"));
		element.click();
		element = driver.findElement(By.id("description"));
		assertEquals(element.getText(),"La valoración ha variado respecto a los últimos días");
		element = driver.findElement(By.id("alertDate"));
		assertEquals(element.getText(),"2016-07-06 18:11:00.0");
		element = driver.findElement(By.id("nombreRuta"));
		assertEquals(element.getText(),"Camino de Santiago Francés");
		element = driver.findElement(By.id("alertPositive"));
		assertEquals(element.getText(),"2");
		element = driver.findElement(By.id("alertNegative"));
		assertEquals(element.getText(),"5");
		element = driver.findElement(By.id("alertBalance"));
		assertEquals(element.getText(),"-3");
		element = driver.findElement(By.id("completeDescription"));
		assertEquals(element.getText(),"La valoración ha variado en una cantidad mayor a la desviación típica obtenida a partir de los balances de opniones de los últimos 7 días.");
		
		element = driver.findElement(By.linkText("Alertas"));
		element.click();
		element = driver.findElement(By.linkText("Configurar alertas"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("positiveOpinions"))));
		element = driver.findElement(By.id("positiveOpinions"));
		element.sendKeys("1");
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("button"))));
		element = driver.findElement(By.id("button"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("nombreLoginUsuario"))));
		element = driver.findElement(By.id("nombreLoginUsuario"));
		element.click();
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.linkText("Salir"))));
		element = driver.findElement(By.linkText("Salir"));
		element.click();
		driver.close();
	}

}
